export const ROOM_NOT_FOUND = 'room_not_found'
export const ROOM_CREATOR = 'room_creator'
export const ROOM_INVITEE = 'room_invitee'
export const ROOM_MEMBER = 'room_member'
export const ROOM_INIT = 'room_initialization'
